#!/bin/bash

SCRIPT_NAME=$(basename $0)
SCRIPT_PATH=$(dirname $(readlink -f $0))

function do_exit() {
    code=${1:?exit code is missing} && shift
    [ $# -gt 0 ] && echo "$@"
    exit $code
}

function do_update() {
    # update pytest
    [ $# -lt 1 ] && { pip3 install -U pytest && pytest --version || do_exit 2 "pytest update failed."; }
    # update specified module
    module=${1:?module name should be specified.}
    pip3 install -U $module || do_exit 2 "$module update failed."
}

function do_pytest() {
    pytest "$@"
}

function do_zen_of_python() {
    python3 -m this
}

function do_list_commands() {
    # each python script for command starts with 'p'.
    for scr in $(ls p*.py 2>/dev/null); do
        mod=${scr%.py}
        cmd=${mod#p}
        desc=$(python3 -c "import $mod; print($mod.SHORTDESC)" 2>/dev/null)
        [ -n "$desc" ] && printf "%s -- %s\n" "$cmd" "$desc"
    done
}


USAGE="$SCRIPT_NAME -- Practical PYthon examples

$SCRIPT_NAME <cmd> [<cmd_options...>]

$(grep '^##:' $0 | sed 's/^##://')
$(cd $SCRIPT_PATH/src && do_list_commands)
"
[ $# -lt 1 ] && do_exit 0 "$USAGE"
cmd=$1 && shift

cd $SCRIPT_PATH
case "$cmd" in
##:zen      display zen of python
zen|this) do_zen_of_python "$@" ;;
##:update   update python required modules. (default:pytest)
update) do_update "$@" ;;
##:pytest   perform pytest under the tests/ directory.
pytest) do_pytest "$@" ;;
##:
##:Commands by python script:
*) script="src/p${cmd}.py" && [ -f $script ] &&
    { python3 $script "$@" || do_exit $?; } ||
    { do_exit 2 "Unknown command -- ${cmd}"; } ;;
esac
